// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zAmja_Dd1xhYIzliCfHTTKfebJMhEOU',
    appId: '1:1038389858842:web:e96637fb912ec1a9b977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    authDomain: 'whatapp-4a56b.firebaseapp.com',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    measurementId: 'G-Y5BBTX2JDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9P9jOPK-JwkueDELVDqK8SUP_I8TpmpY',
    appId: '1:1038389858842:android:8ae40aa3ca446e93b977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfTElvzLr05zo5N7O1vJilqrZTkzuVWc',
    appId: '1:1038389858842:ios:a59ba7133ceac394b977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    iosBundleId: 'com.example.whatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfTElvzLr05zo5N7O1vJilqrZTkzuVWc',
    appId: '1:1038389858842:ios:9e0c348228b67261b977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    iosBundleId: 'com.example.mhap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8zAmja_Dd1xhYIzliCfHTTKfebJMhEOU',
    appId: '1:1038389858842:web:00a542eb635db132b977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    authDomain: 'whatapp-4a56b.firebaseapp.com',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    measurementId: 'G-8C4W6VF1FL',
  );

}