// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfTElvzLr05zo5N7O1vJilqrZTkzuVWc',
    appId: '1:1038389858842:web:your-web-app-id',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    authDomain: 'whatapp-4a56b.firebaseapp.com',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    measurementId: 'your-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCfTElvzLr05zo5N7O1vJilqrZTkzuVWc',
    appId: '1:1038389858842:android:dud9vldo174m4opogastoh04m7o5d587',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfTElvzLr05zo5N7O1vJilqrZTkzuVWc',
    appId: '1:1038389858842:ios:52672242fcc9eeebb977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    iosClientId: '1038389858842-sd09a2klg5if853nnbvnpel6v5ldd2vc',
    iosBundleId: 'com.jeoungtaeju.whatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfTElvzLr05zo5N7O1vJilqrZTkzuVWc',
    appId: '1:1038389858842:ios:52672242fcc9eeebb977a3',
    messagingSenderId: '1038389858842',
    projectId: 'whatapp-4a56b',
    storageBucket: 'whatapp-4a56b.firebasestorage.app',
    iosClientId: '1038389858842-sd09a2klg5if853nnbvnpel6v5ldd2vc',
    iosBundleId: 'com.jeoungtaeju.whatapp',
  );
}
